### ISSUE TITLE
If your gonna steal...

### ISSUE THREAD

**Issue by milliorn** [AnilSeervi/DevFolio#6]
...my code in my PR I pushed up here, delete it, and push it up as your own, I have you know, I have a fork of my work, and others can see it, and what you did. Even if you delete this repo, I still have the fork, and the history.

https://github.com/AnilSeervi/DevFolio/commit/650cbbef5c5e132321ef51e7b8626d98f11276ad

https://github.com/milliorn/DevFolio/commits/lighthouse-accessibility
https://github.com/milliorn/DevFolio/commits/lighthouse-performance

Proves what you did.  I didn't ask for anything, I was simply volunteering an open source repo. If you don't want contributions, then change the settings accordingly. Don't be shameful.

**Comment by AnilSeervi** [comment]
I had already wanted to do the required lighthouse audit changes to the project and I once again thank you for pushing me to do it.

When you opened #4, I realized that you had not followed the documentation and I myself came to realize that it had been outdated. So I updated the documentation and together resized the images and added more enhancements that would make the lighthouse scores better(Not that it matters a lot).

But I agree that I could have suggested to you itself the changes and had updated the docs in a separate PR, my apologies for that. Nonetheless feel free to contribute anything that helps and I'll make sure it gets merged :)
